version: '3.4'

services:
  fastapi_backend:
    image: fastapi_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../docker_container_logs:/code/logs
    ports:
      - 4000:4000

    env_file: .env
    logging:
      driver: local
      options:
        mode: "non-blocking"
        max-buffer-size: "2m"
        max-size: "10m"
        max-file: "3"

    restart: always
